# Generated by Django 4.0 on 2022-01-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_filme', models.CharField(max_length=255, verbose_name='Título')),
                ('ano_filme', models.IntegerField(verbose_name='Ano')),
                ('descricao_filme', models.TextField(verbose_name='Descrição')),
                ('ganhou_oscar', models.BooleanField(default=False, verbose_name='Ganhou Oscar?')),
                ('idade_permitida', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3, verbose_name='Maiores de 18 anos?')),
                ('data_criacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
